version: '3.8'

services:
  postgres:
    image: postgres
    container_name: cse_db
    restart: always
    environment:
      POSTGRES_USER: cseadmin
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: cse_portal
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6543:5432"

volumes:
  pgdata:
